name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-android-kernel:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc
      - run: mkdir customkernelcd customkernel
      - run: git clone https://github.com/bravesoul349/kernel_google_wahoo.git
      - run: mv kernel_google_wahoo src
      - run: git clone https://github.com/mvaisakh/gcc-arm.git
      - run: mv gcc-arm tc32
      - run: git clone https://github.com/mvaisakh/gcc-arm64.git
      - run: mv gcc-arm64 tc
      - run: ls -a
