name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-android-kernel:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set up environment
        run: sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc
      - name: git clone
        run: |
          sudo mkdir /home/works&&cd /home/works
          pwd
          mkdir customkernel&&cd customkernel
          pwd
          ls
          git clone https://github.com/bravesoul349/kernel_google_wahoo.git
          mv kernel_google_wahoo src
          ls
          git clone https://github.com/mvaisakh/gcc-arm.git
          mv gcc-arm tc32
          ls
          git clone https://github.com/mvaisakh/gcc-arm64.git
          mv gcc-arm64 tc
          ls
